### ISSUE TITLE
反馈一个关于弓箭伤害计算BUG，希望作者看到

### ISSUE THREAD

**Issue by Szczecin** [dzxrly/MHWIBDmgCalculator#15]
测试情况：
黑龙弓（基础444攻击，120龙属性），克制一次属性，两次会心，一次防御；
猫饭攻击力up大，猫的射击术；
服用药物鬼人药大，怪力种子，鬼人粉尘；带有力量之爪，力之护符；
技能搭配为挑战者7，攻击7，无伤3，通常箭强化2，散弹刚射强化2，超会心3；
测试对象为普通冰咒龙：头部破坏后肉质55 20，软化后是66 20；
得到的伤害是四蓄平射104，四蓄刚射95（软化后）；
而计算器显示结果是四蓄平射104，四蓄刚射105（软化后）；
（冰咒的怒后补正应该是1.15到1.2左右，但我在计算时没选，不然计算得到伤害会更高）

造成四蓄刚射软化后计算伤害偏高推测是因为把通常箭强化2的增幅也算进了刚射里面，希望作者能看到进行修改，万分感谢

**Comment by dzxrly** [comment]
谢谢老哥反馈！
一次动作计算时只能选择对应的强化技能，比如刚射就只能选择散弹刚射强化而不能同时勾选通常弹强化，因为这一块代码不太好改所以只能这样操作了

**Comment by dzxrly** [comment]
因为最近实在没时间这个问题只能先用上述的解决方案，后面我有时间了会对此部分逻辑进行修改

**Comment by Szczecin** [comment]
> 因为最近实在没时间这个问题只能先用上述的解决方案，后面我有时间了会对此部分逻辑进行修改

Fine.加油

**Comment by dzxrly** [comment]
感谢反馈ヾ(●´∇｀●)ﾉ
